name = "StackOverflow"
uuid = "1a8df32f-26ad-40b8-8029-212bc012bd57"
authors = ["Logan Kilpatrick <lok026@g.harvard.edu>"]
version = "0.1.0"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
CodecZlib = "0.6.0"
Documenter = "0.24.2"
HTTP = "0.8.8"
JSON = "0.21.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
